version: "3.8"

services:
    wallet-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - DATABASE_URL=postgres://user:password@db:5432/wallet_db?sslmode=disable
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=wallet_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data:
